### ISSUE TITLE
Sorry this is not regarding a bug

### ISSUE THREAD

**Issue by pieman64** [jmetzmeier/python-crontab-debian#1]
I have just started to use python-crontab and I was wondering what the file_cron facility is for? I know it can be used in Windows and the OS doesn't have crontab but why would you use it Windows?

I am trying to put together an application that will run on unix and Windows machines. I think I am ok with crontab for unix but is there anyway of interfacing pyhton-crontab with Windows Scheduler?
Thanks.

**Comment by jmetzmeier** [comment]
This repo is only for the Debian packaging of the python-crontab software. The projects home is here: https://bugs.launchpad.net/python-crontab

You should ask your question there.

**Comment by pieman64** [comment]
Does your github run on the Raspberry Pi (Debian Wheezy / Jessie)?

**Comment by jmetzmeier** [comment]
Yes, the resulting Debian package should run on a Raspberry Pi. It is available in Jessie.
